version: "3.7"

# https://codeception.com/docs/12-ParallelExecution
services:

  codecept:
    image: codeception/codeception
    command: run
    depends_on:
      - chrome
      - web
    volumes:
      - .:/project

  web:
    image: php:7-apache
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: percona:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-password

  chrome:
    image: selenium/standalone-chrome:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4444:4444"